"""
Download and prepare Python code for pre-training.
Uses code_search_net Python subset (publicly available, no gating).
Writes JSONL format compatible with mlx-pretrain.
"""
import argparse
import json
import os
import hashlib
from datasets import load_dataset
from tqdm import tqdm

AUTO_GENERATED_MARKERS = [
    "# auto-generated",
    "# generated by",
    "# do not edit",
    "# automatically generated",
    "# this file is generated",
    "# machine generated",
]


def is_auto_generated(content: str) -> bool:
    first_lines = content[:500].lower()
    return any(marker in first_lines for marker in AUTO_GENERATED_MARKERS)


def passes_quality_filter(content: str, min_chars: int = 100, max_chars: int = 50000) -> bool:
    if len(content) < min_chars or len(content) > max_chars:
        return False
    if is_auto_generated(content):
        return False
    lines = content.split("\n")
    non_empty = sum(1 for l in lines if l.strip())
    if non_empty < 3:
        return False
    return True


def deduplicate_hash(content: str, seen_hashes: set) -> bool:
    h = hashlib.md5(content.encode()).hexdigest()
    if h in seen_hashes:
        return False
    seen_hashes.add(h)
    return True


def main():
    parser = argparse.ArgumentParser(description="Prepare Python code corpus for pre-training")
    parser.add_argument("--output-dir", type=str, default="data")
    parser.add_argument("--max-examples", type=int, default=500000,
                        help="Maximum number of examples to process")
    parser.add_argument("--val-ratio", type=float, default=0.02)
    args = parser.parse_args()

    os.makedirs(args.output_dir, exist_ok=True)
    train_path = os.path.join(args.output_dir, "python_train.jsonl")
    val_path = os.path.join(args.output_dir, "python_val.jsonl")

    print("Loading code_search_net Python dataset (streaming)...")
    ds = load_dataset("code_search_net", "python", split="train", streaming=True)

    seen_hashes = set()
    train_count = 0
    val_count = 0
    skipped = 0
    total_chars = 0

    train_file = open(train_path, "w", encoding="utf-8")
    val_file = open(val_path, "w", encoding="utf-8")

    try:
        pbar = tqdm(desc="Processing Python code")
        for i, example in enumerate(ds):
            if train_count + val_count >= args.max_examples:
                break

            code = example.get("whole_func_string", "")
            if not code:
                code = example.get("func_code_string", "")
            if not code:
                skipped += 1
                continue

            if not passes_quality_filter(code):
                skipped += 1
                continue

            if not deduplicate_hash(code, seen_hashes):
                skipped += 1
                continue

            doc = example.get("func_documentation_string", "")
            if doc and not code.startswith('"""') and not code.startswith("'''"):
                text = f'"""{doc}"""\n{code}'
            else:
                text = code

            record = json.dumps({"text": text}, ensure_ascii=False)

            is_val = (train_count + val_count) % int(1 / args.val_ratio) == 0
            if is_val:
                val_file.write(record + "\n")
                val_count += 1
            else:
                train_file.write(record + "\n")
                train_count += 1

            total_chars += len(text)
            pbar.update(1)
            pbar.set_postfix(
                train=train_count, val=val_count,
                skipped=skipped, mb=f"{total_chars / 1e6:.0f}"
            )

        pbar.close()
    finally:
        train_file.close()
        val_file.close()

    approx_tokens = total_chars / 3.5
    print(f"\nDone!")
    print(f"  Train examples: {train_count}")
    print(f"  Val examples:   {val_count}")
    print(f"  Skipped:        {skipped}")
    print(f"  Total chars:    {total_chars / 1e6:.1f}M")
    print(f"  ~Tokens:        {approx_tokens / 1e6:.0f}M (estimate)")
    print(f"  Output:         {train_path}, {val_path}")


if __name__ == "__main__":
    main()
